import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';
import PageWrapper from '@/Components/PageWrapper';
import Navbar from '@/Components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Framer App Simple',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={`${inter.className} bg-gray-100 h-screen`}>
				<Navbar />

				<PageWrapper>{children}</PageWrapper>
			</body>
		</html>
	);
}
